# Name given to this workflow.
name: First Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "first-job"
  first-job:
    # The type of runner that the job will run on
    # We have multiple runners at our disposal, such as Linux, Windows, MacOS, self-hosted.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Greeting
        run: echo "Hello, world!"
      - name: Print goodbye
        run: echo "Done - goodbye"
