name: Test Project

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository code
        uses: actions/checkout@v3
      - name: List directories
        run: ls -la
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd /resources/second-action-react-demo
          npm ci
      - name: Run tests
        run: npm test